name: JJT.IO 
pygments: true
exclude: ["Gemfile*","bower.json","bower_components","scss","compass", "CNAME"]
prose:
  rooturl: '_posts'
  siteurl: 'http://jjt.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "text"
          label: "Category"
          value: ""
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
