name: JJT.IO 
pygments: true
exclude: ["Gemfile*","bower.json","scss","compass", "CNAME", "public",
  "node_modules", "bower_components"]
destination: public
prose:
  rooturl: '_posts'
  siteurl: 'http://jjt.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
